### A Python List is More Than Just a List

In [11]:
import numpy as np

In [12]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [15]:
type(L2[0])

str

In [16]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

### Fixed-Type Arrays in Python

In [19]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating Arrays from Python Lists

In [20]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [22]:
# Upcast
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [24]:
# Explicitly setting data type
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [25]:
# Nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating Arrays from Scratch

In [26]:
# Create a length-10 integer array filled with zeroes
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [29]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.47416102, 0.157987  , 0.71507801],
       [0.96893266, 0.17584375, 0.74431562],
       [0.1772386 , 0.69701945, 0.49886298]])

In [34]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.3163982 ,  0.20448677,  0.28317062],
       [ 0.37425442,  0.42223949, -1.33762869],
       [ 0.53405769, -0.99294104, -0.03033709]])

In [35]:
# Create a 3x3 array of random integers in the interval [0,10)
np.random.randint(0, 10, (3, 3))

array([[3, 6, 6],
       [9, 4, 9],
       [8, 3, 5]])

In [36]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
# Create an unitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])

### Numpy Standard Data Types

In [38]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [40]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

## The Basics of Numpy Arrays

### Numpy Array Attributes

In [45]:
import numpy as np
np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [46]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape )
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [47]:
print("dtype: ", x3.dtype)

dtype:  int32


In [48]:
print("itemsize: ", x3.itemsize, "bytes")
print("nbytes: ", x3.nbytes, "bytes")

itemsize:  4 bytes
nbytes:  240 bytes


### Array Indexing: Accessing Single Elements

In [49]:
x1

array([5, 0, 3, 3, 7, 9])

In [50]:
x1[0]

5

In [51]:
x1[4]

7

In [52]:
x1[-1]

9

In [53]:
x1[-2]

7

In [54]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [55]:
x2[0, 0]

3

In [56]:
x2[2, 0]

1

In [57]:
x2[2, -1]

7

In [58]:
x2[0, 0] = 12

In [59]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [61]:
# Value is truncated - array was initially of type int
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

### Array Slicing: Acessing Subarrays

In [62]:
# Notation x[start:stop:step]

#### One-dimensional subarrays

In [63]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
x[:5]

array([0, 1, 2, 3, 4])

In [65]:
x[5:]

array([5, 6, 7, 8, 9])

In [66]:
x[4:7]

array([4, 5, 6])

In [67]:
x[::2]

array([0, 2, 4, 6, 8])

In [68]:
x[1::2]

array([1, 3, 5, 7, 9])

In [71]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [72]:
x[5::-2]

array([5, 3, 1])

#### Multidimensional subarrays

In [73]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [74]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [77]:
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [79]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Acessing array rows and columns

In [81]:
print(x2[:, 0]) # First column of x2

[12  7  1]


In [82]:
print(x2[0, :]) # First row of x2

[12  5  2  4]


In [83]:
print(x2[0]) # Equivalent to x2[0, :]

[12  5  2  4]


#### Subarrays as no-copy views

In [84]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [85]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [86]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [87]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


#### Creating copies of arrays

In [88]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [89]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [90]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Reshaping of Arrays

In [92]:
grid = np.arange(1, 10).reshape((3, 3))

In [93]:
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [97]:
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [98]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [99]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [100]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### Array Concatenation and Splitting

#### Concatenation of arrays

In [101]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [102]:
# Concatenate multiple arrays
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [105]:
# Concatenate two-dimensional arrays
grid = np.array([[1, 2, 3],
               [4, 5, 6]])

In [104]:
# Concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [106]:
# Concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [107]:
# Arras of mixed dimensions, use np.vstack and np.hstack
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                [6, 5, 4]])

In [109]:
# Vertically stack arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [110]:
# Horizontally stack the arrays
y = np.array([[99],
             [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

#### Splitting of arrays

In [112]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [116]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [117]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [118]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
