### Aggregations: Min, Max, and Everything in Between

#### Summing the Values in an Array

In [1]:
import numpy as np

L = np.random.random(100)
sum(L)

52.99678359631443

In [2]:
np.sum(L)

52.99678359631442

In [3]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

121 ms ± 45.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.43 ms ± 420 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### Minimum and Maximum

In [4]:
min(big_array), max(big_array)

(2.2831894118668927e-06, 0.9999987261849858)

In [5]:
np.min(big_array), np.max(big_array)

(2.2831894118668927e-06, 0.9999987261849858)

In [6]:
%timeit min(big_array)
%timeit np.min(big_array)

82.1 ms ± 29.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
480 µs ± 19.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
print(big_array.min(), big_array.max(), big_array.sum())

2.2831894118668927e-06 0.9999987261849858 500148.19427065924


#### Multidimensional Aggregates

In [8]:
M = np.random.random((3, 4))
print(M)

[[0.24859586 0.31318951 0.87103872 0.23696136]
 [0.39102999 0.46842285 0.96473691 0.9587393 ]
 [0.95546009 0.56835123 0.00561517 0.8886802 ]]


In [9]:
M.sum()

6.870821196003728

In [10]:
M.min(axis=0)

array([0.24859586, 0.31318951, 0.00561517, 0.23696136])

In [11]:
M.max(axis=1)

array([0.87103872, 0.96473691, 0.95546009])